/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import abstracto.ListaEmpleados;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Isra
 */
public class Hija1 extends javax.swing.JInternalFrame {
    private int num_empleados;
    private final DefaultTableModel model;
    /**
     * Creates new form Hija1
     */
    public Hija1() {
        initComponents();
        model = new DefaultTableModel();
        model.addColumn("NSS");
        model.addColumn("Nombre");
        model.addColumn("Apelidos");
        model.addColumn("Salario");
        model.addColumn("Salario IVA");
        model.addColumn("Ventas");
        model.addColumn("Tarifa Comisión");
        model.addColumn("Salario Tarifa Comisión");
        this.jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 102, 51));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Clase Abstracta");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Cantidad:");

        jButton1.setText("GENERAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(402, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            this.num_empleados=Integer.parseInt(this.jTextField1.getText());
            this.model.setNumRows(0);
            ListaEmpleados.generarEmpleados(this.num_empleados);
            for (int i = 0; i < ListaEmpleados.EMPLEADOS.size(); i++) {
                this.model.addRow(new Object[]{
                   ListaEmpleados.EMPLEADOS.get(i).getNSS(),
                   ListaEmpleados.EMPLEADOS.get(i).getNombre(),
                   ListaEmpleados.EMPLEADOS.get(i).getApellidos(),
                   String.valueOf(ListaEmpleados.EMPLEADOS.get(i).getSalario()),
                   ListaEmpleados.DEC_FORMAT.format(ListaEmpleados.EMPLEADOS.get(i).getSalarioIva()),
                   String.valueOf(ListaEmpleados.EMPLEADOS.get(i).getVentas()),
                   ListaEmpleados.DEC_FORMAT.format(ListaEmpleados.EMPLEADOS.get(i).getTarifasComision()),
                   ListaEmpleados.DEC_FORMAT.format(ListaEmpleados.EMPLEADOS.get(i).getSalarioTarifaComision())
                });
            }
            this.jTable1.setModel(this.model);
        }catch(NumberFormatException e){}
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
